name: cook
description: "Cook It Yourself"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  dio: ^5.8.0+1
  shared_preferences: ^2.5.3
  infinite_scroll_pagination: ^5.1.0
  animations: ^2.0.11
  uuid: ^4.5.1
  intl: ^0.20.2
  dartz: ^0.10.1
  get_it: ^8.0.3
  provider: ^6.1.5
  google_fonts: ^6.2.1
  flutter_dotenv: ^5.1.0
  
  # Firebase
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  firebase_storage: ^12.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.10

flutter:
  uses-material-design: true
  assets:
    - assets/cooking_logo.jpg
    - .env

# هذا القسم يجب أن يكون خارج قسم flutter تمامًا
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/cooking_logo.jpg
  color_dark: "#212121"
  image_dark: assets/cooking_logo.jpg
  
  # إضافة هذه الخيارات لتحسين حجم الصورة
  fullscreen: true  # وضع ملء الشاشة
  android: true
  ios: true
  
  # تعديل حجم الصورة (يمكنك ضبط هذه القيم)
  android_gravity: center
  ios_content_mode: scaleAspectFill
  
  android_12:
    image: assets/cooking_logo.jpg
    icon_background_color: "#FF9800"
    image_dark: assets/cooking_logo.jpg
    icon_background_color_dark: "#212121"
  
  web: false
