name: cook
description: "Cook It Yourself - تطبيق وصفات الطبخ"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  dio: ^5.8.0+1
  shared_preferences: ^2.5.3
  infinite_scroll_pagination: ^4.0.0
  animations: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.10

flutter:
  uses-material-design: true
  assets:
    - lib/data/recipes.json
    - assets/cooking_logo.jpg

# هذا القسم يجب أن يكون خارج قسم flutter تمامًا
flutter_native_splash:
  color: "#FF9800"
  image: assets/cooking_logo.jpg
  color_dark: "#212121"
  image_dark: assets/cooking_logo.jpg
  
  # إضافة هذه الخيارات لتحسين حجم الصورة
  fullscreen: true  # وضع ملء الشاشة
  android: true
  ios: true
  
  # تعديل حجم الصورة (يمكنك ضبط هذه القيم)
  android_gravity: center
  ios_content_mode: scaleAspectFill
  
  android_12:
    image: assets/cooking_logo.jpg
    icon_background_color: "#FF9800"
    image_dark: assets/cooking_logo.jpg
    icon_background_color_dark: "#212121"
  
  web: false
